version: '3.8'

services:
  # Backend API
  trading-bot-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: smart-trading-bot-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./src:/app/src  # Mount source code for live reload
      - ./tests:/app/tests
      - ./examples:/app/examples
    environment:
      - PYTHONPATH=/app/src
      - DATA_DIR=/data
      - DB_PATH=/data/app.db
      - LOG_LEVEL=DEBUG
      - DEBUG_MODE=true
      - TRADING_ENABLED=true
      - ORDER_CONFIRMATION_REQUIRED=true
      - MAX_OPEN_POSITIONS=5
      - MAX_RISK_PER_TRADE=2.0
      - MIN_RISK_REWARD_RATIO=3.0
      - EXCHANGE=binance_futures
      - WS_URL=wss://fstream.binance.com/ws
      - REST_URL=https://fapi.binance.com
      - DEFAULT_COMMISSION=0.001
      - DEFAULT_SLIPPAGE=0.0001
      - DEFAULT_INITIAL_CAPITAL=10000.0
      - DATA_STORAGE_FORMAT=parquet
      - DATA_RETENTION_DAYS=365
      - DATA_COMPRESSION=true
      - RELOAD=true
    env_file:
      - .env
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - trading-network-dev

  # Frontend Development Server
  trading-bot-web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: smart-trading-bot-web-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules  # Exclude node_modules from volume mount
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - trading-bot-api
    networks:
      - trading-network-dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  trading-network-dev:
    driver: bridge
